url: http://localhost:8085/v1/graphql
headers:
  X-Hasura-Admin-Secret: my-secret
git:
  name: <uname>
  email: <email>
  token: <token>
  remote: https://<uname>:<token>@github.com/<uname>/auto-test.git
  repo_name: auto-test
  reports_dir: stage
queries:
  - name: users
    tools: [k6, autocannon, wrk2]
    execution_strategy: REQUESTS_PER_SECOND
    rps: 500
    duration: 5s
    queries:
          - query: |
              mutation MyMutation {
                insert_user_one(object: {name: "test"}) {
                  id
                }
              }
          - query: |
              mutation MyMutation {
                insert_user_one(object: {name: "sakjgb"}) {
                  id
                }
              }
          - query: |
              mutation MyMutation {
                insert_user_one(object: {name: "algkbl"}) {
                  id
                }
              }